version: "3"
services:
  db:
    image: mysql:5
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity
    ports:
      - "8111:8111"
    links:
      - db
    depends_on:
      - db
  teamcity-agent-01:
    image: jetbrains/teamcity-agent
    container_name: agent001
    privileged: true
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=AGENT-001
      - DOCKER_IN_DOCKER=start
    links:
      - teamcity
    depends_on:
      - teamcity
  teamcity-agent-02:
    image: jetbrains/teamcity-agent
    container_name: agent002
    privileged: true
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=AGENT-002
      - DOCKER_IN_DOCKER=start
    links:
      - teamcity
    depends_on:
      - teamcity